import base64
import os
from pathlib import Path

from azure.ai.projects import AIProjectClient
from azure.identity import DefaultAzureCredential
from dotenv import load_dotenv


# Store files generated by the agent in a local output folder.
OUTPUT_DIR = Path("agent_outputs")


def get_output_path(filename):
    """Create a unique path for generated files."""
    # Create the output folder and avoid overwriting an existing file.
    OUTPUT_DIR.mkdir(exist_ok=True)
    file_name = Path(filename).name
    stem = Path(file_name).stem or "output"
    suffix = Path(file_name).suffix
    output_path = OUTPUT_DIR / file_name

    counter = 1
    while output_path.exists():
        output_path = OUTPUT_DIR / f"{stem}_{counter}{suffix}"
        counter += 1

    return output_path


def save_bytes(file_bytes, filename):
    """Save binary content to a local file."""
    # Save the file bytes using a unique local output path.
    output_path = get_output_path(filename)
    with open(output_path, "wb") as file_handle:
        file_handle.write(file_bytes)
    return output_path


def save_image(image_data, filename):
    """Save base64 image data to a file."""
    # Decode the image data and save it as a local file.
    return save_bytes(base64.b64decode(image_data), filename)


def download_container_file(openai_client, annotation, downloaded_files):
    """Download a cited container file once and return its local path."""
    # Use the container and file IDs to avoid downloading the same file twice.
    cache_key = (annotation.container_id, annotation.file_id)
    if cache_key in downloaded_files:
        return downloaded_files[cache_key]

    # Retrieve the generated file from the agent's container.
    file_content = openai_client.containers.files.content.retrieve(
        file_id=annotation.file_id,
        container_id=annotation.container_id,
    )

    # Save the downloaded file locally.
    output_path = save_bytes(
        file_content.read(),
        annotation.filename or f"{annotation.file_id}.bin",
    )
    downloaded_files[cache_key] = output_path
    return output_path


def format_output_text(content_item, openai_client, downloaded_files):
    """Replace sandbox file citations with local file paths."""
    # Process the response text and replace generated-file references with local paths.
    text = content_item.text or ""
    replacements = []
    referenced_files = set()

    # Find files referenced in the agent response.
    for annotation in content_item.annotations or []:
        if getattr(annotation, "type", "") != "container_file_citation":
            continue

        output_path = download_container_file(
            openai_client,
            annotation,
            downloaded_files,
        )
        replacement_text = f"{annotation.filename} (saved to {output_path})"
        referenced_files.add(output_path)

        # Replace the cited text using the annotation positions when available.
        start_index = getattr(annotation, "start_index", None)
        end_index = getattr(annotation, "end_index", None)
        if start_index is not None and end_index is not None:
            replacements.append(
                (start_index, end_index, replacement_text)
            )
            continue

        # Fall back to replacing the annotation text directly.
        annotated_text = getattr(annotation, "text", "")
        if annotated_text:
            text = text.replace(annotated_text, replacement_text)

    # Apply replacements from the end so the text positions remain valid.
    for start_index, end_index, replacement_text in sorted(
        replacements,
        reverse=True,
    ):
        text = f"{text[:start_index]}{replacement_text}{text[end_index:]}"

    return text, referenced_files


def main():
    # Load the project endpoint and agent name from the .env file.
    load_dotenv()
    project_endpoint = os.environ.get("PROJECT_ENDPOINT")
    agent_name = os.environ.get("AGENT_NAME", "it-support-agent")

    # Stop the application if the Microsoft Foundry endpoint is missing.
    if not project_endpoint:
        print("Error: PROJECT_ENDPOINT environment variable not set")
        print("Please set it in your .env file or environment")
        return

    print("Connecting to Microsoft Foundry project...")

    # Create an Azure credential using the signed-in user's identity.
    credential = DefaultAzureCredential()

    # Create a client for the Microsoft Foundry project.
    project_client = AIProjectClient(
        credential=credential,
        endpoint=project_endpoint
    )

    # Get the OpenAI client used to interact with the agent.
    openai_client = project_client.get_openai_client()

    # Retrieve the existing agent created in the previous lab.
    print(f"Loading agent: {agent_name}")
    agent = project_client.agents.get(agent_name=agent_name)
    print(f"Connected to agent: {agent.name} (id: {agent.id})")

    # Create a conversation to keep the user's messages together.
    conversation = openai_client.conversations.create(items=[])
    print(f"Conversation created (id: {conversation.id})")

    # Start the interactive terminal chat with the agent.
    print("\n" + "=" * 60)
    print("IT Support Agent Ready!")
    print("Ask questions, request data analysis, or get help.")
    print("Type 'exit' to quit.")
    print("=" * 60 + "\n")

    while True:
        # Read the next question from the user.
        user_input = input("You: ").strip()

        # Exit the application when the user enters an exit command.
        if user_input.lower() in ["exit", "quit", "bye"]:
            print("Goodbye!")
            break

        # Ignore empty input and wait for the next question.
        if not user_input:
            continue

        # Add the user's question to the current conversation.
        openai_client.conversations.items.create(
            conversation_id=conversation.id,
            items=[
                {
                    "type": "message",
                    "role": "user",
                    "content": user_input,
                }
            ],
        )

        print("\n[Agent is thinking...]")

        # Send the conversation to the selected Microsoft Foundry agent.
        response = openai_client.responses.create(
            conversation=conversation.id,
            extra_body={
                "agent_reference": {
                    "name": agent.name,
                    "type": "agent_reference",
                }
            },
            input="",
        )

        # Track whether the response contained text or generated files.
        handled_output = False
        downloaded_files = {}
        referenced_files = set()
        image_count = 0

        # Process the response returned by the agent.
        if hasattr(response, "output") and response.output:
            for item in response.output:
                item_type = getattr(item, "type", "")

                # Display text responses and download referenced files.
                if item_type == "message" and getattr(
                    item,
                    "content",
                    None,
                ):
                    for content_item in item.content:
                        if getattr(
                            content_item,
                            "type",
                            "",
                        ) != "output_text":
                            continue

                        formatted_text, message_files = format_output_text(
                            content_item,
                            openai_client,
                            downloaded_files,
                        )
                        referenced_files.update(message_files)

                        if formatted_text:
                            print(
                                f"\nAgent: {formatted_text}\n"
                            )
                            handled_output = True

                # Display any direct text returned by the response.
                elif hasattr(item, "text") and item.text:
                    print(f"\nAgent: {item.text}\n")
                    handled_output = True

                # Save generated images such as charts locally.
                elif item_type == "image":
                    image_count += 1
                    filename = f"chart_{image_count}.png"

                    if hasattr(item, "image") and hasattr(
                        item.image,
                        "data",
                    ):
                        file_path = save_image(
                            item.image.data,
                            filename,
                        )
                        print(
                            f"\n[Agent generated a chart - "
                            f"saved to: {file_path}]"
                        )
                    else:
                        print("\n[Agent generated an image]")

                    handled_output = True

            # Report generated files that were not already shown in the response.
            for file_path in downloaded_files.values():
                if file_path not in referenced_files:
                    print(
                        f"\n[Agent generated a file - "
                        f"saved to: {file_path}]"
                    )
                    handled_output = True

        # Display the fallback response text when no output items were handled.
        if (
            not handled_output
            and hasattr(response, "output_text")
            and response.output_text
        ):
            print(f"\nAgent: {response.output_text}\n")


# Start the application when this file is run directly.
if __name__ == "__main__":
    main()